import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as PDFLib from 'pdf-lib';
import * as M from '../dist/rules.mjs';import {exportSheet} from '../dist/export.mjs';import {R,advancedSoldier} from './fixture.mjs';
function complete(c){const s=M.fresh();s.career=c.id;s.species=c.species.includes('Human')?'Human':c.species[0];s.name=`Test ${c.name}`;s.speciesSkills=M.speciesSkillSlots(R,s).slice(0,5).map(x=>x.key);s.randomTalents=['Read/Write','Super Numerate','Cardsharp','Attractive'].slice(0,R.species[s.species].randomTalents);let left=8;for(const slot of M.careerSkillSlots(R,s,1)){if(left&&M.freeSkills(R,s)[slot.name]<3||left&&!M.freeSkills(R,s)[slot.name]){s.careerSkills[slot.key]=1;left--;}}s.freeTalent=M.careerTalentOptions(R,s).find(t=>!M.invalidTalent(R,s,t));s.wealth={amount:50,currency:'brass pennies'};s.spells=M.spellGrants(R,s).flatMap(g=>g.choices.slice(0,g.count).map(x=>x.name));return s;}
test('every Career can produce a valid new character from book choices',()=>{for(const c of R.careers){const s=complete(c);assert.deepEqual(M.validation(R,s),[],c.name);const d=M.derive(R,s);for(const k of M.KEYS)assert.ok(Number.isFinite(d.stats[k]),`${c.name} ${k}`);}});
test('Arcane Lore grants include common Arcane Spells (p.242)',()=>{const s=complete(R.careers.find(c=>c.id==='wizard'));s.ledger.push({type:'talent',name:'Arcane Magic (Fire)',cost:100,tick:true});const g=M.spellGrants(R,s).find(x=>x.category==='Fire');assert.equal(g.choices.length,32);assert.ok(g.choices.some(x=>x.name==='Aethyric Armour'));});
test('spell metadata does not absorb adjacent labels or prose',()=>{for(const x of R.spells){assert.ok(x.range&&x.target&&x.duration,x.name);assert.ok(!/Range:|Target:|Duration:/.test(x.cn||''),x.name);assert.ok(x.duration.length<100,x.name);assert.ok(/[.!?]$/.test(x.text),x.name);}});
test('filled PDF retains editable fields, matching checkbox state, and complete companion pages',async()=>{globalThis.PDFLib=PDFLib;const bytes=await exportSheet(R,advancedSoldier(),fs.readFileSync(new URL('../dist/assets/character-sheet.pdf',import.meta.url)),JSON.parse(fs.readFileSync(new URL('../dist/data/sheet-fields.json',import.meta.url))));const doc=await PDFLib.PDFDocument.load(bytes),form=doc.getForm();assert.equal(form.getFields().length,556);assert.ok(doc.getPageCount()>2);for(const [name,value]of Object.entries({WS_Current:'46',Fate:'4',Fortune_Max:'3',XP_Spent:'1000',Status_1:'Silver 2',Wounds_Total:'13',Enc_Total:'5'}))assert.equal(form.getTextField(name).getText(),value,name);assert.ok(form.getCheckBox('Adv_C1_R1_01').isChecked());assert.ok(!form.getCheckBox('Adv_C1_R1_06').isChecked());const checkbox=form.getCheckBox('Adv_C1_R1_01');assert.equal(checkbox.acroField.getValue().toString(),checkbox.acroField.getWidgets()[0].getAppearanceState().toString());});
test('one-point advances survive editable PDF export',async()=>{globalThis.PDFLib=PDFLib;const s=complete(R.careers.find(c=>c.id==='soldier'));M.purchase(R,s,'char','WS',1);M.purchase(R,s,'skill','Cool',1);const bytes=await exportSheet(R,s,fs.readFileSync(new URL('../dist/assets/character-sheet.pdf',import.meta.url)),JSON.parse(fs.readFileSync(new URL('../dist/data/sheet-fields.json',import.meta.url))));const form=(await PDFLib.PDFDocument.load(bytes)).getForm(),d=M.derive(R,s);assert.equal(form.getTextField('WS_Advances').getText(),'1');assert.equal(form.getTextField('WS_Current').getText(),String(d.stats.WS));assert.equal(form.getTextField('Cool_Adv').getText(),String(Math.round(d.skills.Cool*5)));assert.equal(form.getTextField('XP_Spent').getText(),String(d.spent));assert.ok(form.getCheckBox('Adv_C1_R1_01').isChecked());assert.ok(form.getCheckBox('Adv_C1_R1_02').isChecked());});
test('Priest exports all six Blessings through the attached record',async()=>{globalThis.PDFLib=PDFLib;const s=complete(R.careers.find(x=>x.id==='priest'));s.freeTalent='Bless (Sigmar)';assert.equal(M.knownSpells(R,s).length,6);const bytes=await exportSheet(R,s,fs.readFileSync(new URL('../dist/assets/character-sheet.pdf',import.meta.url)),JSON.parse(fs.readFileSync(new URL('../dist/data/sheet-fields.json',import.meta.url))));const d=await PDFLib.PDFDocument.load(bytes);assert.ok(d.getPageCount()>3);assert.ok(d.getForm().getTextField('Spell_1_Name').getText().startsWith('Blessing'));assert.equal(d.getForm().getTextField('Spell_1_Range').getText(),'6 yards');});
