"""Reviewed Night Parade import. PDF text/layout checked before authoring these records."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PDF = Path(r"C:\Users\ninod\Downloads\The Night Parade.pdf")
SHA = "f8bb99e7da5163cbb094208f78c183410b1d1b0490d01188f09a8dbddca25b53"
assert hashlib.sha256(PDF.read_bytes()).hexdigest() == SHA
PACK = ROOT / "dist/data/books/night-parade"
PACK.mkdir(exist_ok=True)

def write(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")

def identity(kind, slug):
    return f"night-parade:{kind}:{slug}"

def trait(name, value=""):
    if name == "Corrupted":
        label = {1:"Minor",2:"Moderate"}[int(value)]
        return {"name":"Corruption", "value":label, "adaptation":f"Legacy: printed Corrupted ({value}) uses core Corruption ({label}), by user-approved conversion."}
    if name == "Diseased":
        return {"name":"Disease", "value":"", "adaptation":"Legacy: printed Diseased uses core Disease; the book does not identify a disease, so the GM must name one explicitly."}
    return {"name": name, "value": str(value)}

def skill(names, amount):
    return {"options": names if isinstance(names, list) else [names], "bonus": amount, "count": 1}

def talent(names, note=""):
    return {"options": names if isinstance(names, list) else [names], "ranks": 1, **({"adaptation": note} if note else {})}

restore = "Proposed Legacy adaptation approved by the user: restore the template's absent Characteristics from a zero baseline. Wights lose Construct so their printed mental increases and Leadership can work in Fifth Edition."
liche_note = "Legacy: Dark Magic (Necromancy) uses core Arcane Magic (Necromancy); absent Characteristics increased by this template start from zero, as approved. The printed template explicitly removes Construct."
mount_note = "Legacy: the printed zero Intelligence, Willpower and Fellowship become absent Characteristics under core Construct. Printed Flight uses core Fly."
colour_names = [f"Arcane Magic ({x})" for x in ["Beasts", "Death", "Fire", "Heavens", "Life", "Light", "Metal", "Shadows"]]
common_magic_skills = [skill("Cool", 20), skill("Intimidate", 15), skill("Language (Magick)", 15), skill("Language (Nehekharan)", 10), skill("Lore (Magic)", 10), skill("Perception", 10)]
common_talents = [talent("Arcane Magic (Necromancy)", "Legacy: printed Dark Magic (Necromancy) is replaced by the core Arcane Magic (Necromancy) Talent."), talent("Hardy"), talent("Menacing"), talent("Petty Magic"), talent("Read/Write"), talent("Second Sight")]
lich_gear = [{"label": "Hand Weapon", "names": ["Hand Weapon"], "kind": "weapon"}, {"label": "Staff — choose its core weapon profile", "kind": "weapon", "group": "Polearm", "choose": True}]

def template(slug, name, page, adjustments, eligibility, **extra):
    return {"id": identity("template", slug), "name": name, "page": page, "source": {"book": "night-parade", "page": page}, "adjustments": adjustments, "skills": [], "talents": [], "traits": [], "optionalTraits": [], "gear": [], "notes": [], "eligibility": eligibility, **extra}

templates = [
    template("mass-grave-dead", "Mass Grave Dead", 8, {"S": 20, "T": 20, "Ag": -5, "Dex": -5}, "undead", setStats={"BS": 0}, traits=[trait("Corrupted", 1), trait("Painless"), trait("Stupid"), trait("Swarm")], optionalTraits=[trait("Bestial"), trait("Regeneration"), trait("Size", "Large"), trait("Territorial")], adaptation="Legacy: printed Corrupted (1) uses core Corruption (Minor), by user-approved conversion."),
    template("liche-corpsemaster", "Liche Corpsemaster", 8, {"WS": 10, "BS": 20, "T": 10, "I": 15, "Int": 40, "WP": 45, "Fel": 10}, "zombie", removeTraits=["Construct"], restoreStats=["BS", "Int", "WP", "Fel"], skills=[skill("Channelling (Any)", 10), *common_magic_skills], talents=[talent(colour_names), *common_talents], gear=lich_gear, trappings="Mouldering Robes; Pouches containing ritual components", magicGroups=[{"categories": ["Petty"], "count": 3}, {"categories": ["Arcane"], "count": 2}, {"categories": ["Necromancy"], "count": 1}], matchWind=True, adaptation=liche_note, notes=["Staff is not silently mapped to Quarterstaff: explicitly select its core Polearm profile. Descriptive robes and ritual components have no invented quantities or statistics."]),
    template("liche-lord", "Liche Lord", 8, {"WS": 20, "BS": 20, "T": 20, "I": 30, "Dex": 10, "Int": 65, "WP": 70, "Fel": 20}, "zombie", removeTraits=["Construct"], restoreStats=["BS", "Int", "WP", "Fel"], skills=[skill("Channelling (Shyish)", 20), skill("Cool", 30), skill("Intimidate", 25), skill("Language (Magick)", 30), skill("Language (Nehekharan)", 20), skill("Leadership", 20), skill("Lore (Magic)", 30), skill(["Melee (Basic)", "Melee (Polearm)"], 15), skill("Perception", 20)], talents=[talent("Aethyric Attunement"), talent("Arcane Magic (Death)", "Legacy: printed Arcane Magic (Shyish) uses core Arcane Magic (Death)."), *common_talents[:2], talent("Instinctive Diction"), talent("Magical Sense"), talent("Menacing", "Legacy: printed Menacing 2 becomes one rank, respecting the core Talent's nonrepeatable limit."), *common_talents[3:], talent("War Wizard")], gear=lich_gear, trappings="Mouldering Robes; Pouches containing ritual components", magicGroups=[{"categories": ["Petty"], "count": 4}, {"categories": ["Arcane", "Death"], "count": 8}, {"categories": ["Necromancy"], "count": 3}], adaptation=liche_note + " Printed Shyish uses Death; Menacing 2 becomes one rank.", notes=["Printed Aetheric Attunement uses the canonical spelling Aethyric Attunement."]),
]
for champion in [False, True]:
    templates.append(template("wight-champion" if champion else "wight", "Wight Champion" if champion else "Wight", 9, {"WS": 30, "BS": 20, "S": 20, "T": 25, "I": 20, "Int": 30, "WP": 40, "Fel": 30} if champion else {"WS": 15, "BS": 10, "S": 10, "T": 15, "I": 10, "Int": 10, "WP": 10, "Fel": 10}, "undead", removeTraits=["Construct"], restoreStats=["BS", "Int", "WP", "Fel"], skills=[skill("Intimidate", 20 if champion else 10), skill(["Melee (Basic)", "Melee (Two-Handed)"], 20), *([skill("Language (Classical)", 30), skill("Lore (Warfare)", 30), skill("Lore (History)", 20)] if champion else []), skill("Leadership", 20 if champion else 10), skill("Perception", 20 if champion else 10)], talents=[talent("Combat Aware"), *([talent("Combat Reflexes")] if champion else []), talent("Drilled"), talent("Menacing"), talent("Robust"), *([talent("Strike Mighty Blow", "Legacy: printed Strike Mighty Blow 2 becomes one rank, respecting the core nonrepeatable limit."), talent("War Leader")] if champion else [])], gear=[{"label": "Hand Weapon", "names": ["Hand Weapon"], "kind": "weapon"}, {"label": "Plate Armour — choose a core quick profile" if champion else "Mail Armour — choose a core quick profile", "kind": "armour", "quick": True, "choose": True}, {"label": "Shield or Two-Handed Weapon", "kind": "weapon-or-shield", "choose": True}], adaptation=restore + (" Printed Strike Mighty Blow 2 becomes one rank." if champion else ""), notes=["The supplement allows its undead advancement templates on basic Skeletons or Zombies (p. 9). This app uses the Fifth Edition foundations, not the duplicated older basic profiles. Select a core armour profile explicitly; no armour pieces are inferred."]))
mount_traits = [trait("Construct"), trait("Dark Vision"), trait("Fear", 2), trait("Painless"), trait("Undead"), trait("Unstable")]
templates += [template("skeletal-steed", "Skeletal Steed", 10, {"WS": -10, "BS": -10, "I": -10, "Ag": -10}, "mount", removeTraits=["Fly"], traits=mount_traits, armour=2, optionalTraits=[trait("Corruption", "Minor"), trait("Infected"), trait("Territorial")], adaptation=mount_note), template("rotting-mount", "Rotting Mount", 10, {"M": -1, "I": -25, "Ag": -20}, "mount", halveStats=["WS"], halveTraits=["Fly"], traits=mount_traits, optionalTraits=[trait("Diseased"), trait("Distracting"), trait("Infected"), trait("Infestation"), trait("Territorial")], adaptation=mount_note)]
vigor = "Any Undead within 8 of the Corpse Cart are no longer subject to Unstable; the Cart itself remains subject to it. Necromancy spells cast within 8 receive +20. These effects end when the Cart is destroyed."
balefire = "Replaces the normal Necromancy casting benefit of Vigor Mortis: all Lore (Magic) checks within 8 suffer −20. The protection of nearby Undead from Unstable remains."
cart_notes = ["Die Hard is removed by user decision; no Fifth Edition equivalent or resurrection rule is granted.", "Rear is covered by Fifth Edition Size/Stomp: a larger creature loses Momentum to make a Melee (Brawling) Free Attack dealing Strength Bonus Damage (core pp. 360–361).", "The five Flailing Limbs use +11 rather than printed +7: core Large Size adds SB 4. This is an approved Legacy adaptation.", "Vigor Mortis/Balefire retain the printed range ‘within 8’; the book specifies no distance unit. Printed +20/−20 bonuses stay reference text, without automatic conversion or live aura tracking."]
cart = {"id": identity("creatures", "corpse-cart"), "name": "Corpse Cart", "page": 19, "source": {"book": "night-parade", "page": 19}, "example": False, "stats": dict(zip(["M", "WS", "BS", "S", "T", "I", "Ag", "Dex", "Int", "WP", "Fel", "W"], [4,20,None,40,50,5,10,10,None,None,None,36])), "size": "Large", "category": "Undead", "toughnessBonus": 5, "skills": [], "talents": [], "traits": [trait("Construct"),trait("Constrictor"),trait("Corrupted",2),trait("Dark Vision"),trait("Fear",3),trait("Painless"),trait("Size","Large"),trait("Undead"),trait("Unstable"),trait("Vigor Mortis")], "optionalTraits": [trait("Balefire Brazier"),trait("Diseased"),trait("Distracting"),trait("Infected"),trait("Infestation"),trait("Trained","Mount")], "attacks": [{"name": "Flailing Limb " + str(i+1), "skill": 20, "damage": 11, "printedDamage": 7, "text": "One of five Flailing Limbs", "optional": False, "adaptation": cart_notes[2]} for i in range(5)], "armour": [{"name": "Corpse Cart Armour", "ap": 3, "locations": "Head, Arms, Body, Legs", "optional": False, "quick": False, "shield": False}], "spells": [], "sections": {}, "notes": cart_notes, "adaptation": "Legacy: Rear uses core Size/Stomp, five Flailing Limbs become +11 under Large Size, and Die Hard is removed by user decision."}
write(ROOT / "dist/gm/sources/night-parade.json", {"schemaVersion": 1, "id": "night-parade", "source": {"file": PDF.name, "sha256": SHA}, "summary": "Seven undead templates & Corpse Cart", "profiles": [cart], "templates": templates, "training": [], "traits": [{"id": identity("trait", slug), "name": name, "page": 19, "source": {"book": "night-parade", "page": 19}, "parameter": "", "text": text} for slug,name,text in [("vigor-mortis","Vigor Mortis",vigor),("balefire-brazier","Balefire Brazier",balefire)]]})
write(PACK / "manifest.json", {"schemaVersion":1,"id":"night-parade","title":"The Night Parade","shortTitle":"Night Parade","edition":4,"version":"1.0.0","kind":"supplement","dependsOn":["core"],"source":{"file":PDF.name,"sha256":SHA},"compatibility":{"reviewed":True,"notes":["Seven GM templates use Fifth Edition foundations and approved zero-baseline/Construct conversions. Named characters are excluded.","Approved core Talent replacements and repeat limits; Corpse Cart uses Size/Stomp and +11 Damage, with Die Hard removed.","Three Ride specialisations are shared options. No extra free PC Advances, Species or Careers."]},"files":{"rules":"rules.json","coverage":"coverage.json","referenceEntries":"reference-entries.json"}})
write(PACK / "rules.json", [{"id":identity("skills","ride"),"path":["skillOptions","Ride"],"operation":"append","value":["Rotting Mount","Skeletal Steed","Corpse Cart"],"page":10,"reason":"Printed undead mount specialisations; their optional GM +20 bonuses are separate from PC creation allocations."}])
refs = [{"id":identity("reference",slug),"name":name,"category":"rule","topic":"Undead","page":page,"text":text} for slug,name,page,text in [("templates","Applying Undead Advancement Templates",3,"Add or subtract the template's Advances to the base creature's Characteristics and add its listed Skills, Talents and Trappings. Recalculate Wounds when Strength, Toughness or Willpower changes."),("mounts","Undead Mounts",10,"The mount templates apply to creatures that could normally have Trained (Mount), of Large Size or smaller. Halved values round down. Skeletons, Zombies, Wights and Liches may take Ride (Rotting Mount) +20 or Ride (Skeletal Steed) +20; Liches and Necromancers may also take Ride (Corpse Cart) +20."),("vigor-mortis","Vigor Mortis",19,vigor),("balefire-brazier","Balefire Brazier",19,balefire)]]
write(PACK / "reference-entries.json", refs)
write(PACK / "coverage.json", {"schemaVersion":1,"records":[],"features":[{"id":identity("feature",slug),"name":name,"status":status,"source":{"book":"night-parade","page":page},"reason":reason} for slug,name,status,page,reason in [("gm","Undead templates and Corpse Cart","adapted",8,"Seven reviewed templates and one foundation use approved Fifth Edition conversions."),("auras","Vigor Mortis and Balefire Brazier","reference-only",19,"Actual selected abilities print descriptions; live aura effects are not automated."),("named","Named NPCs and adventures","deferred",12,"Named characters, warband management and adventure prose excluded by scope."),("die-hard","Die Hard","unavailable",19,"Removed by user decision; no direct core equivalent.")]]})
index = ROOT / "dist/data/books/index.json"
registry = json.loads(index.read_text(encoding="utf-8"))
if not any(x["id"] == "night-parade" for x in registry["packs"]):
    registry["packs"].append({"id":"night-parade","path":"night-parade/manifest.json"})
write(index, registry)
audit_path = ROOT / "scripts/search-reference-review.json"
review = json.loads(audit_path.read_text(encoding="utf-8"))
review["books"]["night-parade"] = {"sourceHash":SHA,"publishedSHA256":hashlib.sha256((PACK / "reference-entries.json").read_bytes()).hexdigest(),"entries":len(refs),"areas":[{"first":3,"last":19,"topic":"Undead template procedures, mount Skills and Corpse Cart abilities"}],"records":[*[{"id":r["id"],"name":r["name"],"page":r["page"],"disposition":"included"} for r in refs],*[{"id":t["id"],"name":t["name"],"page":t["page"],"disposition":"included","reason":"Retained for GM creation; excluded from global search."} for t in [*templates,cart]],{"id":identity("excluded","named-npcs"),"name":"Old Jasper, Mheava, The Herald and Charnel Chorus","page":"12–14","disposition":"excluded","reason":"Named character foundations excluded by user scope."},{"id":identity("excluded","basic-profiles"),"name":"Basic Skeleton and Zombie","page":9,"disposition":"existing","reason":"Use the supplied Fifth Edition core foundations, not duplicate Fourth Edition profiles."},{"id":identity("excluded","adventures"),"name":"Setting, warband disposition and adventure hooks","page":"4–18","disposition":"excluded","reason":"No standalone mechanical reference or creator option."}]}
write(audit_path, review)

